name "bash-completion"
maintainer       "Gabor Veszi"
maintainer_email "veszig@done.hu"
license          "Apache 2.0"
description      "Installs bash-completion and sets global use flag"
version          "0.1"
supports         "gentoo"
depends          "gentoo"
name 		 "bash-completion"
