name "sudo"
maintainer       "Gabor Veszi"
maintainer_email "veszig@done.hu"
license          "Apache 2.0"
description      "Installs and configures sudo"
version          "0.1"
depends          "gentoo"
